### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by sirhill** [CMTA/CMTA20#2]
I am very happy that the C-Layer provided a major contribution to the CMTA20. 
More can be obtain here : [https://github.com/c-layer/contracts](https://github.com/c-layer/contracts)

**Comment by sirhill** [comment]
"The smart contract was designed by CMTA's Technical Committee, with contributions from Lenz & Staehelin, Mt Pelerin (source code lead author), Swissquote, Taurus Group, and Tokenestate."

MtPelerin is unfortunately neither the lead, nor an author as their contribution is not mentioning the original author.

**Comment by veorq** [comment]
This matter originates from a conflict between @sirhill and his former company, and this is not the place to discuss these, especially when worded in such an inappropriate way.

**Comment by sirhill** [comment]
It was mentionned on your README.md that it was precisely the place to discuss it.
Please update it to reflect the situation.

Stealing open source code is definetely an appropriate behavior.

**Comment by robert-zaremba** [comment]
Open Source is great. It allow us to grow a way faster then ever before. 
Thanks to Open Source, we can share the knowledge and experience.
The only thing to respect is the license, which in case of Open Source is reduced to copy rights.
