### ISSUE TITLE
API finality

### ISSUE THREAD

**Issue by dspicher** [CMTA/CMTA20#6]
Hi
I am interested in using the CMTA20 standard for asset tokens. To this end, I'd like to get a sense of how mature the interface is: Is it expected to undergo significant changes in the future, or fairly mature?
I'm thankful for any insight you can provide.

**Comment by veorq** [comment]
Hello! The current interface is expected to remain stable, with possible extensions in the near future.

**Comment by dspicher** [comment]
Thanks for the answer.
