### ISSUE TITLE
Function setContact to be removed from IContactable interface

### ISSUE THREAD

**Issue by 3sGgpQ8H** [CMTA/CMTA20#8]
Interface `IContactible` defines common API for entities that have associated contact information.  The interface defines `contact` function to retrieve current contract information either on- or off-chain, and `LogContectSet` event to monitor for contract information changes.  So far so good.

However, the interface also defines `setContact` function that looks odd.  Different implementations may use different strategies for managing contract information.  Some implementations may keep contract information immutable, e.g. hardcod is, similar to how `name` and `symbol` properties of a token are usually being managed.  Some other implementations may rely on external on-chain repository for storing contract information, such as ENS, and thus updating contract information will be performed via interaction with some other contracts, but not with the contract implementing IContactable.  I believe, `setContact` function should be removed from the interface.

Also, even name `LogContectSet` does not follow event naming rules followed by ERC-20 and other common smart contract APIs.  Prefix `Log` is redundant and events are usually being named via nouns, such as `ContactUpdate`.  However, it is probably too late to change.

**Comment by veorq** [comment]
Thanks for reporting this issue (and the others!), we're discussing your feedback and will follow up in the issues' threads :)
